### ISSUE TITLE
"do" in lua is not colored

### ISSUE THREAD

**Issue by Emexus** [noplay/vscode-rainbow-end#11]
If you create multiple while do's and for do's, the "do" is colored as if this extension wasn't in effect at all, "while", "for", "if", "function" and "end" are colored however

**Comment by polvalente** [comment]
This seems like it just needs to be added as a "neutralToken"

**Comment by Emexus** [comment]
Doesn't seem like there's an option for that

**Comment by polvalente** [comment]
@Emexus has your issue been solved in #17 ?

**Comment by Emexus** [comment]
I'm sorry for the late answer!
Sadly it's not completely fixed, Lua has single "do end" blocks for scoping variables, those seem to be making problems :/
![image](https://user-images.githubusercontent.com/20151443/71776652-9f737d00-2f95-11ea-94f5-baa40e907db6.png)
